### ISSUE TITLE
Impossible to connect to a database on an non-Platform.sh environment

### ISSUE THREAD

**Issue by jepster** [platformsh/symfonyflex-bridge#4] opened 2018-03-05 22:54 UTC
If I install this composer package on platform.sh, the (MariaDB) database connection works fine. However, it prevents database access on my local environment and others. 

In file platformsh-flex-env.php the function

`mapPlatformShEnvironment() `

has an if-case in line 18: 

`if (!getenv('DATABASE_URL')) { `

which is true on an non-platform.sh environment. Afterwards the environment is set in line 41: 

`$_ENV['DATABASE_URL'] = $dbUrl;`

I suggest improving the if-case in line 18.

**Comment by Crell** [comment] 2018-03-06 16:39
Seems like this is a duplicate of #3.  Folding these together...

**Closed as completed by Crell** 2018-03-06 16:39 UTC
