### ISSUE TITLE
rabbitmq support for messenger?

### ISSUE THREAD

**Issue by patie** [platformsh/symfonyflex-bridge#34] opened 2020-04-18 11:15 UTC
Hi, what about support of symfony messenger? MESSENGER_TRANSPORT_DSN variable

**Comment by Crell** [comment] 2020-04-20 13:58
There's some WIP on that front here: #28 

Right now there's some design questions to sort out, plus I'd like to get the Elasticsearch support (#25) landed first to avoid commit collisions.

(Input/help on either of those points is most welcome.  Especially testing to make sure it actually works as intended on a real application.)

**Comment by Crell** [comment] 2021-01-26 17:12
This has since been added.

**Closed as completed by Crell** 2021-01-26 17:12 UTC
